### ISSUE TITLE
Is it on Melpa stable?

### ISSUE THREAD

**Issue by lgmoneda** [Fuco1/org-timeline#1]
Although the readme says I can install it from Melpa, I can't find this package on [Melpa stable](https://stable.melpa.org/#/?q=org-timeline).

**Comment by Fuco1** [comment]
Well not every package on melpa is on melpa stable.  I can tag a release, it will be there tomorrow.

**Comment by Fuco1** [comment]
Actually there are tags, latest is 0.1.3.

Is this even on melpa proper?

**Comment by Fuco1** [comment]
No it's not.  I'll send them a PR.

**Comment by Fuco1** [comment]
https://github.com/melpa/melpa/pull/5686
