### ISSUE TITLE
Currently working on the last two TODO items (tooltip and navigable blocks)

### ISSUE THREAD

**Issue by aizensoosuke** [Fuco1/org-timeline#12]
Hovering the blocks would :
1. Highlight the block
2. Display the corresponding headline (not content) and its TODO state in the minibuffer.

This would rely on the `'help-echo` text-property. Contrary to org-agenda, it would not display a "mouse-2 or RET jump to file" tip. I assume users will try clicking on blocks anyway.

Clicking on the blocks could either :
- Behave just like if the user hit `RET` (or `SPC`) on the corresponding agenda line (i.e. open the tasks' file)
- Simply move in the agenda to the corresponding tasks' line.

Both would rely on saving the position of the tasks in the agenda buffer when building the tasks list. It might be more reliable to use the tasks' org-marker, but I can't seem to find the proper way to do that. 
I'll begin with implementing the second option.

**Comment by aizensoosuke** [comment]
This is done now, everything is in pull request #11.

> This would rely on the 'help-echo text-property. Contrary to org-agenda, it would not display a "mouse-2 or RET jump to file" tip. I assume users will try clicking on blocks anyway.

Using the minibuffer works, but the info appears a little far from the timeline. I'm going to change this to display the info on a new line in the timeline, that appears only when a block is hovered.

> Both would rely on saving the position of the tasks in the agenda buffer when building the tasks list. It might be more reliable to use the tasks' org-marker, but I can't seem to find the proper way to do that.

I think using org-marker when clicking blocks would be useless, as the way I'm doing this now is quite reliable. It can also very easily be adapted to open a new buffer with the tasks' file opened. **Maybe this should actually an option for the user**.

**Comment by aizensoosuke** [comment]
All of this is done. My final version of those features was pushed to #11.

**Comment by Fuco1** [comment]
> Using the minibuffer works, but the info appears a little far from the timeline. I'm going to change this to display the info on a new line in the timeline, that appears only when a block is hovered.

This sounds to me like it would flicker and move the rest of the agenda up and down, is it so?  Minibuffer is standard place where people would naturally look for some tool tips, see also `eldoc` package.  Maybe it could be implemented in terms of that, although it might conflict with the org usage of that.

If you decide to put it in the buffer, I would at least make it configurable (using a `'help-echo` as alternative).

**Comment by aizensoosuke** [comment]
> > Using the minibuffer works, but the info appears a little far from the timeline. I'm going to change this to display the info on a new line in the timeline, that appears only when a block is hovered.
> 
> This sounds to me like it would flicker and move the rest of the agenda up and down, is it so? Minibuffer is standard place where people would naturally look for some tool tips, see also `eldoc` package. Maybe it could be implemented in terms of that, although it might conflict with the org usage of that.
> 
> If you decide to put it in the buffer, I would at least make it configurable (using a `'help-echo` as alternative).

I'm actually using `'help-echo` for both in-buffer info *and* minibuffer info. It basically acts as a hover event-listener.
I can definitely make it configurable, but it behave quite smoothly I think. 

It doesn't flicker at all because I chose not to clean the info, even after the user isn't hovering anymore (there doesn't seem to be any easy way to do that actually). It really just moves the agenda once, unless you click on an event, but I could change that if you don't like it.

Not cleaning also allows the user to just hit RET on the buffer's info line to move to the task.

**Comment by Fuco1** [comment]
I see.  I haven't tested it yet as I don't have access at the moment, but that sounds nice.

**Comment by aizensoosuke** [comment]
I'm letting you know that I'm improving features from #11 in another branch that I'll PR after #11 is merged. 

(namely, I made the info line navigable to the task's *file*)

**Comment by Fuco1** [comment]
I think we can close this now that #11 is merged and #17 is in review.
