### ISSUE TITLE
Horizontal lines around timeline

### ISSUE THREAD

**Issue by aizensoosuke** [Fuco1/org-timeline#14]
Wouldn't it make more sense to have the timeline's horizontal lines (above and below) appear just like on the README screenshot?

![image](https://user-images.githubusercontent.com/26968781/107202159-29dcaa80-69fa-11eb-9600-a4b3e29e158a.png)
 
Right now it is displayed on half a screen, and only at the bottom:

![image](https://user-images.githubusercontent.com/26968781/107202321-5c86a300-69fa-11eb-80ef-0f41b616b0f2.png)

**Comment by Fuco1** [comment]
Yea, sure!  I think it depends on the system's fonts or something and I decided not to tune it further.

**Comment by aizensoosuke** [comment]
I ended up implementing that in one of #16 or #17.
