### ISSUE TITLE
Feature ideas from deopurkar. One line per day, conflict-highlighting. 

### ISSUE THREAD

**Issue by aizensoosuke** [Fuco1/org-timeline#15]
I think [deopurkar's fork](https://github.com/deopurkar/org-timeline/commits/master) has some nice features implemented.

Specifically:
1. Conflicts are not moved to a new line, but overlapping blocks have a specific face.
2. Each day has its own line

I think it would be even nicer to add, if there are any clocked entries, a new line below the entry day's one, specifically for clocked items. That way you would have:

        |05:00|06:00|...
    Mon        --event-blocks--
      $        --clocked-items--
    Tue        --event-blocks--
    Wed        --event-blocks--
    ...

The way to handle conflicts could be a user option. 

I'll be working on this.

I'm not sure if there's a way to credit deopurkar for that, if it ever were to be implemented here. If there is, please let me know how to do that.

**Comment by aizensoosuke** [comment]
All of this is now done, see #16.

**Comment by aizensoosuke** [comment]
That's the result: 
![image](https://user-images.githubusercontent.com/26968781/107290370-b0c76c80-6a66-11eb-9727-0f1038a09a4f.png)

Monday has a clock item, Thursday has overlapping items. All blocks are interactive. Everything is configurable.

**Comment by Fuco1** [comment]
For credits, you can add some comment in the code linking to the forked repo.  Since they did not write the code (you did) we shouldn't put the name in the author, just in case some day in the future this will be merged up-stream... so we don't have FSF-legal issues.

**Comment by aizensoosuke** [comment]
Okay, I did mention deopurkar in one or two comments. I'll add the link the link to their repo instead.

**Comment by Fuco1** [comment]
You can also leave an issue in their repo saying that we are pulling the features upstream.  Sometimes people can't be bothered to contribute the code back (which is completely okay!), but if someone else does it they will happily switch to the "official" version.

**Comment by aizensoosuke** [comment]
Okay I'll do that, then
