### ISSUE TITLE
Clarity of the code

### ISSUE THREAD

**Issue by aizensoosuke** [Fuco1/org-timeline#18]
After #17, `org-timeline--generate-timeline` has become quite crowded.

It might be a good idea to either break it down or structure is with comments?
Macros could also simplify a thing or two, I think.

If you'd like me to try and make things clearer, let me know. 
For now I think I'll stop at #17, unless of course you request changes or suggest new features.

**Comment by Fuco1** [comment]
Yea, we can simplify code, but ideally after everything is merged, you can than do a refactoring pull request with the clean up.

Long functions are not usually problematic so long as they do one thing (or some logical sequence of steps).  If there are unrelated pieces they can be moved to another function.

Macros are... problematic :D They are best kept for syntactic purposes only, i.e. creating new control structures or flow operators.

**Comment by aizensoosuke** [comment]
Okay, I'll do that after #17 is merged.
