### ISSUE TITLE
void function org-timeline--display-info when I move point on first line of timeline table

### ISSUE THREAD

**Issue by stardiviner** [Fuco1/org-timeline#21]
I got error when I move point one the first line of timeline table:

```
redisplay--pre-redisplay-functions: (wrong-number-of-arguments ((t) (args) "Display the info line") 3) [2 times]
```

I checked out the source code, found it's not implemented.

**Comment by aizensoosuke** [comment]
Try to run `M-x toggle-debug-on-error`, then do what triggered the bug and let us see the traceback that will appear please.

**Comment by stardiviner** [comment]
Here is the backtrace after toggled debug on error:

```
Debugger entered--Lisp error: (void-function org-timeline--display-info)
  org-timeline--display-info(#<window 201 on *Org Agenda(a)*> 25777 entered)
  cursor-sensor--detect(#<window 201 on *Org Agenda(a)*>)
  run-hook-with-args(cursor-sensor--detect #<window 201 on *Org Agenda(a)*>)
  redisplay--pre-redisplay-functions(nil)
  apply(redisplay--pre-redisplay-functions nil)
  #f(advice-wrapper :before ignore redisplay--pre-redisplay-functions)(nil)
  apply(#f(advice-wrapper :before ignore redisplay--pre-redisplay-functions) nil)
  #f(advice-wrapper :after #f(advice-wrapper :before ignore redisplay--pre-redisplay-functions) zoom--handler)(nil)
  redisplay_internal\ \(C\ function\)()
```

**Comment by aizensoosuke** [comment]
You can try using my PR #19 that adds quite a few features from the version you're using. 
I'm also fixing your issue on master now.

**Comment by aizensoosuke** [comment]
Turns out I can't push to master, so for now you can either use #19, or use the branch [aizensoosuke-patch-1](https://github.com/Fuco1/org-timeline/tree/aizensoosuke-patch-1).

**Comment by stardiviner** [comment]
I tested with your branch, the problem is confirmed fixed. Thanks. Hope be merged soon.
