### ISSUE TITLE
tests: travis configuration problems?

### ISSUE THREAD

**Issue by aizensoosuke** [Fuco1/org-timeline#23]
When I run `cask exec buttercup -L . -L tests` locally (emacs 27.1) the tests run well (except for the problem in #22).

Travis (see [here](https://travis-ci.org/github/aizensoosuke/org-timeline)) only passes the tests for version 25.3, but not 24.* and 26.*. 

- For version 24, it looks like `if-let` wasn't supported. Does `org-timeline` have to support version 24 or could we just let it error?
- For version 26, `cask install` won't run and I don't know enough about Travis to fix this.

**Comment by Fuco1** [comment]
- [ ] #29
