### ISSUE TITLE
feature request: some events from different days appear on the same day line

### ISSUE THREAD

**Issue by pedro-nonfree** [Fuco1/org-timeline#26]
I installed this amazing package this way:

```
(use-package org-timeline :ensure t)
(add-hook 'org-agenda-finalize-hook 'org-timeline-insert-timeline :append)
```

version seems to be `20211110.1952` according to `package-list-packages`

regretably it mixes different day events in the same day (line) which is very confusing

emacs version: 27.2

**Comment by Fuco1** [comment]
Yea, this package can't work with multiple days now.

**Comment by Fuco1** [comment]
related/duplicated in #20 and related pull requests.
