### ISSUE TITLE
I got the timeline grid, but data is empty. 

### ISSUE THREAD

**Issue by anoduck** [Fuco1/org-timeline#27]
Installed the package, and it does add the time grid to the top of my agenda file, but as data goes, it is completely empty. Stupid question: Does timeline primarily just track clocked time? 

Tomorrow, I will try to remember to come back to this issue with more info.

**Comment by anoduck** [comment]
I see now, it only shows tasks that are scheduled, and not those that merely have a deadline.

**Comment by Fuco1** [comment]
Well, anything with a time range which is on the agenda somewhere.

**Comment by anoduck** [comment]
Thanks.
