### ISSUE TITLE
org version requirement?

### ISSUE THREAD

**Issue by Dapuva76** [Fuco1/org-timeline#4]
does this require a certain version of org-mode to function?
I've dl'd it and modified my config file, but it doesn't show up. My
agenda view is set to show the next two weeks, as well as the last week,
not sure if that has any possible impact.

**Comment by Fuco1** [comment]
Can you `M-:` and evaluate `org-agenda-finalize-hook` to see if it exists and contains the hook from this package?

I'm not aware of any specific version requirements, I'm using 9.1.6 and there it works.

You'd need 9+ though probably.

**Comment by Dapuva76** [comment]
Yes, it does exist and contains the hook. I'm using org-mode 9.1.9 on Emacs 25.3.1 (Windows 7)

**Comment by Fuco1** [comment]
Any additional agenda packages?  What happens if you run the function manually inside the agenda?  If you know how to debug elisp code you can walk through the execution.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Edebug.html

**Comment by Dapuva76** [comment]
Found the culprit. Something's not right with my load-path config. Manually loading the file gets timeline working. Sorry for wasting your time!

**Comment by Fuco1** [comment]
No problem, happy it works!

Yea, the hooks don't signal errors and just fail silently so probably Emacs didn't help you much there :D
