### ISSUE TITLE
FR: multi-month view

### ISSUE THREAD

**Issue by mankoff** [Fuco1/org-timeline#5]
I think this is a stretch for the current code, but it is closer to a feature I've been looking for than anything else is. I'd like to see a 3- or 6-month view. Specifically, in Europe it is common to have timelines like this:

![image](https://user-images.githubusercontent.com/145117/45048007-ff44d580-b07a-11e8-9dc4-c4aeb29f8deb.png)

And I would love to be able to create this view in Org. Your code here is closer to this, I think, than calfw.

Of course with that display you have to limit the number of items being shown each day, but Org already provides this feature - I'd only show items with DEADLINE, or multi-day items, or items with a certain tag, for example.

**Comment by Fuco1** [comment]
Yea, I think this could be a separate package. The code here works by scanning the agenda so unless you load an agenda for half a year (which will take an hour) there's not much code to share.

I see @alphapapa liked this, I think a setup reasonably close to this could be achieved with org-super-agenda? By having groupings by month and filters on items with deadline.
