### ISSUE TITLE
Problems with the view of the agenda

### ISSUE THREAD

**Issue by ghost** [Fuco1/org-timeline#6]
I have three problems with the visualization of the agenda.

1. The first is:

![2019-05-17-075453_1163x92_scrot](https://user-images.githubusercontent.com/50729993/57906109-5afd6a80-7868-11e9-867a-ee0238f91583.png)

Instead of to see the lines below correctly, it appear of that way.

2. The second problem is that appear only one day in the timeline, instead of three, as can to see here:
https://raw.githubusercontent.com/Fuco1/org-timeline/master/img/timeline1.png

3. The third problem is that don't show the TODO items in the timeline.

For other hand, I had to load manually org-timeline, autoload didn't work, the same problem that had other user: #4 

Information:
Arch 5.0.10
GNU Emacs 26.2-1
Org-mode 9.1.9

**Comment by Fuco1** [comment]
1. I don't know why that happens.  Try reproducing with a more minimal config.

2. It doesn't show three days. In case there are overlapping events it will place them on multiple lines.  The timeline shows whatever tasks are visible in the agenda.

3. The tasks must have time information associated with them, either as a range or as a `SCHEDULED` value.

**Comment by ghost** [comment]
You're right, the multiple lines only is showed when there are overlapping events.

1. How I could load with the minimal config? (This is for to fix the problems that appear in the screenshot that I uploaded in my previous message).

I used `emacs -Q` and `load-file` on the minibuffer, and then I loaded `org-mode`, `dash`, `org-timeline` and I opened a file in the agenda and the org-timeline doesn't work.

2. There is other problem: org-timeline only detect this:

> * TODO Exam SCHEDULED: <2019-05-17 Fri 19:00-21:00>

And not detect the same but in two lines:
> * TODO Exam
> SCHEDULED: <2019-05-17 Fri 19:00-21:00>

**Comment by Fuco1** [comment]
The first syntax you describe in 2. is, according to my knowledge, not valid org mode.  Anyway, the parsing of this is handled by org-agenda, this package only reads the properties there.

You can use `C-u C-x =` on the first character of a line in org-agenda to see the properties.

**Comment by SSD2019** [comment]
Thanks Fuco1 for this extension. I'm also having a similar problem, where only the time ranges are displayed but not the SCHEDULED times. @user1976  Were you able to get it working?

**Comment by SSD2019** [comment]
I also tried with a fresh config with nothing except org-mode in the latest spacemacs. Clocked and SCHEDULED time ranges are not shown. but other active timestamps are shown.

**Comment by Fuco1** [comment]
Did you open the detailed view, using `l` key in the agenda?

**Comment by SSD2019** [comment]
I do not see a detailed view in the agenda (using the latest version of spacemacs and org) . 
I did try enabling log mode, and still does not show clocked entries and scheduling times.

**Comment by Fuco1** [comment]
The way this works is that the item must show in the agenda and must have the time information attached.

If you go to the item in the agenda, put the cursor on the first column and hit `C-u C-x =` do you see the related text-properties? Most important `duration`.  If it is not set then nothing will show.

**Comment by SSD2019** [comment]
In the related text-properties, scheduled items were having the `type` field set as 'scheduled'. 
But in the code, we were only parsing clock and timestamp type entries. 
After I added scheduled to the list. Its working correctly.      

Line 133:        (when (member type (list "scheduled" "clock" "timestamp"))

Thanks for the hint about looking at the fields in related text properties. 

Also It would great if we can show this org-timeline at the top of agenda?

**Comment by Fuco1** [comment]
OK, we can definitely add the scheduled tasks.  I completely forgot about this check and it didn't come to mind.  PR welcome!

Rendering on top of the agenda should be doable as we do the render in a post-hook.  But the position right now is hard-coded.  I will look into it, it should be really simple.
